version: "3.7"
services:
  db:
    image: "mysql.8.0"
    container_name: myql-container
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/mysql/custom.cnf:/etx/mysql/conf.d/custom.cof
      - ./docker/mysql/Logs:/var/log/mysql

      ports:
        - "3306:3305"
        environment:
          MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
          MYSQL_USER: ${DB_USER}
          MYSQL_PASSWORD: ${DB_PASSWORD}
          MYSQL_DATABASE: ${DB_NAME}
          networks:
            - app



services:

  redis:
    image: redis: 7.0.4
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD"]
    container_name: redis-container
    hostname: redis_standaLone
    labels:
             -"name-redis"
           -"mode=standaLone"
    ports:
     -"6379:6379"
    environment:
             REDIS_PASSWORD: $REDIS_PASSWORD}
             depends on:
               -db
             networks:
               -app

services:

               server:
                 image: ghcr.io/${GITHUB_ACTOR}/spring-backend:latest
                 build:
                 container_name: spring-backend
                 volumes:
                     -appdata:/app
                 depends_on:
                     -db
                 ports:
                     -"7777:7777"
                command:
                     -bash
                    - -c
                     - |
                   /wait-for-it.sh db:3306 -t 15
                   java -jar /app.jar
               networks:
                     -app


                networks:
                   app:
                     driver: bridge

                     volumes:
                       dbdata:
                         driver: loval
                         appdata:
                           driver: local
