SERVER_PORT=7777

CORS_ALLOWED_ORIGINS=http://AWS_PUBLIC_IP:3000

SPRING_APPLICATION_NAME=spring-special-lecture

SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/special_lecture_db?allowpublickeyretrieval=true&usessl=false&serverTimezone=UTC
SPRING_DATASOURCE_USERNAME=eddi
SPRING_DATASOURCE_PASSWORD=eddi@123
SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
SPRING_DATASOURCE_DIALECT=org.hibernate.dialect.MySQL8Dialect

SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=true
SPRING_JPA_OPEN_IN_VIEW=false
SPRING_JPA_DATABASE=mysql
SPRING_JPA_SHOW_SQL=true
SPRING_JPA_GENERATE_DDL=true
SPRING_JPA_HIBERNATE_DDL_AUTO=update

SPRING_DATA_REDIS_HOST=localhost
SPRING_DATA_REDIS_PORT=6379
SPRING_DATA_REDIS_PASSWORD=eddi@123

KAKAO_LOGIN_URL=https://kauth.kakao.com
KAKAO_CLIENT_ID=dia0723_REST_API_KEY
KAKAO_REDIRECT_URI=http://AWS_PUBLIC_IP:7778/kakao-authentication/login
KAKAO_TOKEN_REQUEST_URI=https://kauth.kakao.com/oauth/token
KAKAO_USER_INFO_REQUEST_URI=https://kapi.kakao.com/v2/user/me
